# Deployment를 생성하는 YAML 파일
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-env
  template:
    metadata:
      labels:
        app: my-app-env
    spec:
      containers:
        - name: my-app-container-env
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_cc7b43225a83
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: google_client_secret
